import { connection } from "next/server";
import { routing } from "@/i18n/routing";
import { articlePath } from "@/lib/article-url";
import { hubPath } from "@/lib/hub-url";
import { SITE_NAME, SITE_URL, feedUrl, localizedUrl } from "@/lib/seo";
import { serverFetchNewsList } from "@/lib/server-news";
import { serverFetchTagHubs } from "@/lib/server-tags";
import type { NewsListResponse } from "@/type/fastapi/news";
import type { TagHub } from "@/type/fastapi/tags";

// Rendered per request (connection()) rather than prerendered + ISR: a build or revalidation
// that happens while the backend is down would otherwise pin the degraded output for a full
// period. Caching is the CDN's (Cache-Control) plus the Data Cache of the fetches.
const CACHE_SECONDS = 3600;
const FAILURE_CACHE_SECONDS = 60;

const TOP_TEAMS = 30;
const LATEST_ARTICLES = 20;

// llms.txt lists English URLs only; every page links its own translations via hreflang.
const url = (path: string) => localizedUrl(routing.defaultLocale, path);

/** One line of plain text that is safe inside a markdown link label / list item. */
function inline(text: string): string {
  return text
    .replace(/[\s\p{Cc}]+/gu, " ")
    .trim()
    .replace(/([\\[\]])/g, "\\$1");
}

function link(label: string, href: string, note?: string | null): string {
  const suffix = note ? `: ${inline(note)}` : "";
  return `- [${inline(label)}](${href})${suffix}`;
}

function hubLinks(hubs: TagHub[]): string[] {
  return hubs.flatMap((hub) => {
    const path = hubPath(hub);
    const articles = `${hub.news_count} article${hub.news_count === 1 ? "" : "s"}`;
    return path ? [link(hub.name, url(path), articles)] : [];
  });
}

const INTRO = `# ${SITE_NAME}

> ${SITE_NAME} is a football (soccer) platform: daily league news reports, data-driven match previews with predictions, odds and betting tips, expert perspectives that end in a pick with a confidence level, live match pages (scores, lineups, statistics, head-to-head) and community discussion.

- Languages: English (no URL prefix), Traditional Chinese (/zh-TW), Simplified Chinese (/zh-CN) and Japanese (/ja). The URLs below are the English ones; each page declares its translations with hreflang.
- How the editorial content is made: news reports, match previews and expert perspectives are AI-assisted. They are generated by a language model from API-Football data (fixtures, standings, statistics, odds) and third-party news coverage; the source articles are listed on each article. Traditional Chinese and Japanese are machine translations of the English original; Simplified Chinese is converted from Traditional Chinese.
- Predictions, odds and picks are informational, not betting advice or a guarantee of any result.
- Live scores, lineups, statistics and standings come from API-Football. Posts, comments and votes are written by users.`;

const SECTIONS = `## Sections

${[
  link("News", url("/news"), "Daily league news reports and data-driven match previews"),
  link(
    "Expert Picks",
    url("/our-picks"),
    "Expert perspectives on upcoming matches, each ending in a pick with a confidence level",
  ),
  link("Games", url("/games"), "Fixtures and live scores, with a match page per fixture"),
  link("Stats", url("/stats"), "League standings, team statistics and player statistics"),
  link("Teams", url("/teams"), "Team hubs collecting every article about a team"),
  link("Leagues", url("/leagues"), "League hubs collecting every article about a league"),
  link("Discuss", url("/discuss"), "Community posts and discussion"),
].join("\n")}`;

const MACHINE_READABLE = `## Sitemaps and feeds

${[
  link("Sitemap index", `${SITE_URL}/sitemap.xml`, "All pages, with hreflang alternates"),
  link("News sitemap", `${SITE_URL}/news-sitemap.xml`, "Articles published in the last 48 hours"),
  link("RSS feed", feedUrl(routing.defaultLocale), "The 30 most recent articles (English)"),
].join("\n")}`;

export async function GET() {
  await connection();
  // Both helpers swallow backend errors (-> [] / null): the dynamic sections just drop out.
  const [hubs, news] = await Promise.all([
    serverFetchTagHubs(),
    serverFetchNewsList(1, LATEST_ARTICLES),
  ]);

  const byNewsCount = [...hubs].sort((a, b) => b.news_count - a.news_count);
  const leagues = hubLinks(byNewsCount.filter((hub) => hub.type === "league"));
  const teams = hubLinks(byNewsCount.filter((hub) => hub.type === "team").slice(0, TOP_TEAMS));
  const articles = ((news.data as NewsListResponse | null)?.items ?? [])
    .filter((article) => article.is_published)
    .map((article) =>
      link(article.title, url(articlePath(article)), article.content_preview),
    );

  const sections = [INTRO, SECTIONS];
  if (leagues.length > 0) sections.push(`## Leagues\n\n${leagues.join("\n")}`);
  if (teams.length > 0) sections.push(`## Teams\n\n${teams.join("\n")}`);
  if (articles.length > 0) sections.push(`## Latest articles\n\n${articles.join("\n")}`);
  sections.push(MACHINE_READABLE);

  const cacheSeconds = news.data ? CACHE_SECONDS : FAILURE_CACHE_SECONDS;
  return new Response(`${sections.join("\n\n")}\n`, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": `public, s-maxage=${cacheSeconds}, stale-while-revalidate=${cacheSeconds}`,
    },
  });
}
